name: lendsqr workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: lendsqr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI (lint + test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # NOTE: You wrote 20.19.30 — Node versions are usually like 20.19.0.
          # Use 20.19.0 (or change to '20.x' if you want the latest Node 20).
          node-version: "20.19.0"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test
